# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
gem: [jekyll-paginate, jekyll-gists]

# Setup
title:               개발 잘하고 싶어요
tagline:             'A Jekyll theme'
description:         '공부한 내용 개발 이슈 등을 정리하고 있습니다.'
url:                 https://minomi.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              minho
  url:               https://minomi.github.io
  email:             5minhominho@gmail.com

github:
repo:              https://github.com/minomi

# Custom vars
version:             1.0.0
